import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Generates public/sw.js after the build: a small, dependency-free service
// worker that precaches the hashed build output (cache-first, safe since
// filenames change on every rebuild) plus a couple of static PWA assets,
// and falls back to /offline.html when navigation fails with no network.
// Runtime data (Livewire/API calls) is never cached.
function generateServiceWorker() {
    return {
        name: 'generate-service-worker',
        closeBundle() {
            const manifestPath = path.resolve(__dirname, 'public/build/manifest.json');
            if (!fs.existsSync(manifestPath)) {
                return;
            }

            const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
            const buildAssets = new Set();

            for (const entry of Object.values(manifest)) {
                if (entry.file) buildAssets.add(`/build/${entry.file}`);
                for (const css of entry.css ?? []) buildAssets.add(`/build/${css}`);
                for (const asset of entry.assets ?? []) buildAssets.add(`/build/${asset}`);
            }

            const staticAssets = [
                '/offline.html',
                '/manifest.webmanifest',
                '/images/pwa/icon-192.png',
                '/images/pwa/icon-512.png',
            ];

            const precacheUrls = [...buildAssets, ...staticAssets];
            const cacheVersion = Date.now().toString();

            const swSource = `// Auto-generated by vite.config.js — do not edit by hand.
const CACHE_NAME = 'hp-shell-${cacheVersion}';
const OFFLINE_URL = '/offline.html';
const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 4)};

self.addEventListener('install', (event) => {
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then((cache) => cache.addAll(PRECACHE_URLS))
            .then(() => self.skipWaiting())
    );
});

self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.keys()
            .then((keys) => Promise.all(
                keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
            ))
            .then(() => self.clients.claim())
    );
});

self.addEventListener('fetch', (event) => {
    const { request } = event;
    if (request.method !== 'GET') {
        return;
    }

    const url = new URL(request.url);
    if (url.origin !== self.location.origin) {
        return;
    }

    // Full-page navigations: go to the network, fall back to the cached
    // offline page only when the network is unavailable.
    if (request.mode === 'navigate') {
        event.respondWith(
            fetch(request).catch(() => caches.match(OFFLINE_URL))
        );
        return;
    }

    // Any other precached asset (build output, icons, the manifest): serve
    // from cache first, falling back to the network. Everything else
    // (Livewire/API calls, uncached pages) passes straight through.
    event.respondWith(
        caches.match(request).then((cached) => cached || fetch(request))
    );
});
`;

            fs.writeFileSync(path.resolve(__dirname, 'public/sw.js'), swSource);
        },
    };
}

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/sass/app.scss',
                'resources/js/app.js',
            ],
            refresh: true,
        }),
        generateServiceWorker(),
    ],
});
