<?php

namespace App\Services\Attendance;

use DateTime;
use App\Services\Months;

/**
 * Class SubcontractorHoursDataObject.
 *
 * Helper for reading the data generated by the GetSubcontractorsMonthlyHoursReportService.
 */
class SubcontractorHoursDataObject
{
    /** @var array */
    protected $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    /**
     * Get all the subcontractors from the report.
     *
     * @return array [id => ['name' => string, 'status' => int]]
     */
    public function getSubcontractors()
    {
        $output = [];
        foreach ($this->data as $subID => $info) {
            if ($subID !== 'info') $output[$subID] = $info['subcontractor-info'];
        }
        return $output;
    }

    /**
     * Get all the workers of a subcontractor from the report.
     *
     * @return array [id => ['name' => string, 'status' => int]]
     */
    public function getWorkers(int $subID)
    {
        $output = [];
        foreach ($this->data[$subID]['workers'] ?? [] as $workerID => $info) {
            $output[$workerID] = $info['worker-info'];
        }
        return $output;
    }

    /**
     * Get the hours of a worker for the given date.
     *
     * @return float|NULL NULL if there are no hours
     */
    public function hours(DateTime $date, int $subID, int $workerID)
    {
        $hours = $this->data[$subID]['workers'][$workerID]['attendance'][$date->format('Y-m-d')] ?? NULL;
        return $hours > 0 ? (float) $hours : NULL;
    }

    /**
     * Get the sum of hours of a worker for the whole month.
     *
     * @return float
     */
    public function workerTotal(int $subID, int $workerID)
    {
        return (float) array_sum($this->data[$subID]['workers'][$workerID]['attendance'] ?? []);
    }

    /**
     * Get the cost of a worker for the whole month.
     *
     * @return float
     */
    public function workerCost(int $subID, int $workerID)
    {
        return $this->workerTotal($subID, $workerID) * $this->getHourCost();
    }

    /**
     * Get the sum of hours of all the workers of a subcontractor for the given date.
     *
     * @return float|NULL NULL if there are no hours
     */
    public function subcontractorDayTotal(DateTime $date, int $subID)
    {
        $total = 0;
        foreach ($this->getWorkers($subID) as $workerID => $info) {
            $total += $this->hours($date, $subID, $workerID) ?? 0;
        }
        return $total > 0 ? $total : NULL;
    }

    /**
     * Get the sum of hours of all the workers of a subcontractor for the whole month.
     *
     * @return float
     */
    public function subcontractorTotal(int $subID)
    {
        $total = 0;
        foreach ($this->getWorkers($subID) as $workerID => $info) {
            $total += $this->workerTotal($subID, $workerID);
        }
        return $total;
    }

    /**
     * Get the cost of a subcontractor for the whole month.
     *
     * @return float
     */
    public function subcontractorCost(int $subID)
    {
        return $this->subcontractorTotal($subID) * $this->getHourCost();
    }

    /**
     * Get the sum of hours of all the subcontractors for the given date.
     *
     * @return float|NULL NULL if there are no hours
     */
    public function dayTotal(DateTime $date)
    {
        $total = 0;
        foreach ($this->getSubcontractors() as $subID => $info) {
            $total += $this->subcontractorDayTotal($date, $subID) ?? 0;
        }
        return $total > 0 ? $total : NULL;
    }

    /**
     * Get the sum of hours of all the subcontractors for the whole month.
     *
     * @return float
     */
    public function total()
    {
        $total = 0;
        foreach ($this->getSubcontractors() as $subID => $info) {
            $total += $this->subcontractorTotal($subID);
        }
        return $total;
    }

    /**
     * Get the cost of all the subcontractors for the whole month.
     *
     * @return float
     */
    public function totalCost()
    {
        return $this->total() * $this->getHourCost();
    }

    /**
     * Get the base cost of one work hour.
     *
     * @return float
     */
    public function getHourCost()
    {
        return (float) ($this->data['info']['hour-cost'] ?? 0);
    }

    /**
     * Format a cost value for display.
     *
     * @return string
     */
    public function formatCost($value)
    {
        return number_format((float) $value, 2, ',', '.') . ' €';
    }

    /**
     * Format a hours value for display (no trailing zeros, empty string for NULL).
     *
     * @return string
     */
    public function formatHours($value)
    {
        if ($value === NULL) return '';
        return (string) ((float) $value + 0);
    }

    /**
     * Get all dates for the given month/year.
     *
     * @return array
     */
    public function getDates()
    {
        $dates = $this->data['info']['date'];
        return Months::daysOfMonth($dates['month'], $dates['year']);
    }

    /**
     * Get the month from the data.
     *
     * @return int
     */
    public function getMonth()
    {
        return $this->data['info']['date']['month'];
    }

    /**
     * Get the year from the data.
     *
     * @return int
     */
    public function getYear()
    {
        return $this->data['info']['date']['year'];
    }
}
