<?php

namespace App\Services\Application;

use App\Models\Resources;
use App\Models\Application\AppModule;
use App\Models\Application\AppModuleRoute;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use App\Services\AutoInstallationService;

/**
 * Class AppModulesSyncService.
 * Moves the app modules and their routes (app_modules, app_module_routes) between environments.
 *
 * export() reads them from the local database (see `php artisan app-modules:export`),
 * import() writes them into the current database (the "app_modules_sync" auto-installation type).
 *
 * Import rules:
 *  - rows are matched by ID, then by natural key (module: `module`, route: module + `route_name`).
 *    A row matched by natural key gets the ID from the file, so the next sync matches it by ID.
 *  - `active` is only set when a row is created, so switching a module/route on or off
 *    on the server is not undone by the next sync.
 *  - rows that are not in the file are never deleted.
 *  - the resource is exported by its name (resource IDs differ between databases)
 *    and created on import if it doesn't exist.
 */
class AppModulesSyncService
{
    /**Installation type handled by AutoInstallationService */
    const INSTALLATION_TYPE = 'app_modules_sync';

    /**File the export writes and the auto-installation reads */
    const FILE_NAME = 'app_modules_sync.json';

    /**
     * Path of the sync file in the auto-installations folder.
     *
     * @return string
     */
    public static function filePath(): string
    {
        return app(AutoInstallationService::class)->getInstallationPath() . DIRECTORY_SEPARATOR . self::FILE_NAME;
    }

    /**
     * Export the modules and routes into the sync file (see filePath()).
     *
     * @return array ['modules' => count, 'routes' => count, 'warnings' => [...]]
     */
    public static function exportToFile(): array
    {
        $warnings = [];
        $data = self::export($warnings);

        $content = [
            'type'        => self::INSTALLATION_TYPE,
            'description' => 'App modules and their routes, generated by `php artisan app-modules:export`. Do not edit by hand.',
            'data'        => $data,
        ];

        File::ensureDirectoryExists(dirname(self::filePath()));
        File::put(self::filePath(), json_encode($content, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . "\n");

        return [
            'modules'  => count($data['modules']),
            'routes'   => array_sum(array_map(fn ($module) => count($module['routes']), $data['modules'])),
            'warnings' => $warnings,
        ];
    }

    /**
     * Import the sync file now, through the auto-installer so the run is recorded
     * (the next deploy then skips the file if its data didn't change).
     *
     * @return array counts of created / updated / re-keyed rows
     * @throws \Throwable
     */
    public static function importFromFile(): array
    {
        return app(AutoInstallationService::class)->installFile(self::FILE_NAME);
    }

    /**
     * All modules with their routes, sorted so the file only changes when the data changes.
     *
     * @param array $warnings filled with the problems found while exporting
     * @return array
     */
    public static function export(array &$warnings = []): array
    {
        $resources = Resources::pluck('resources', 'id');
        $routes = AppModuleRoute::orderBy('position')->orderBy('route_name')->orderBy('id')->get()->toBase()->groupBy('module_id');
        $modules = AppModule::orderBy('name')->orderBy('id')->get();

        $orphans = $routes->except($modules->pluck('id')->all());
        foreach ($orphans->flatten() as $route) {
            $warnings[] = "Route \"{$route->route_name}\" ({$route->id}) skipped, its module ({$route->module_id}) doesn't exist.";
        }

        return [
            'modules' => $modules->map(fn (AppModule $module) => [
                'id'         => $module->id,
                'name'       => $module->name,
                'module'     => $module->module,
                'controller' => $module->controller,
                'active'     => (bool) $module->active,
                'routes'     => ($routes[$module->id] ?? collect())->map(function (AppModuleRoute $route) use ($resources, &$warnings) {
                    $resource = NULL;
                    if ($route->resource_id !== NULL && $route->resource_id !== '') {
                        $resource = $resources[$route->resource_id] ?? NULL;
                        if ($resource === NULL) $warnings[] = "Route \"{$route->route_name}\": resource {$route->resource_id} doesn't exist, exported without a resource.";
                    }
                    return [
                        'id'         => $route->id,
                        'title'      => $route->title,
                        'route_name' => $route->route_name,
                        'method'     => $route->method,
                        'active'     => (bool) $route->active,
                        'resource'   => $resource,
                        'position'   => $route->position === NULL ? NULL : (int) $route->position,
                        'divider'    => $route->divider,
                    ];
                })->values()->all(),
            ])->values()->all(),
        ];
    }

    /**
     * Create / update the modules and routes from the exported data, in one transaction.
     *
     * @param array $data the "data" of the installation file
     * @return array counts of created / updated / re-keyed rows
     * @throws \Exception
     */
    public static function import(array $data): array
    {
        if (!isset($data['modules']) || !is_array($data['modules'])) {
            throw new \Exception('app_modules_sync must contain a "modules" list');
        }

        $stats = ['modules_created' => 0, 'modules_updated' => 0, 'routes_created' => 0, 'routes_updated' => 0, 'rekeyed' => 0];

        DB::transaction(function () use ($data, &$stats) {
            foreach ($data['modules'] as $moduleData) {
                $module = self::importModule($moduleData, $stats);
                foreach ($moduleData['routes'] ?? [] as $routeData) {
                    self::importRoute($module, $routeData, $stats);
                }
            }
        });

        return $stats;
    }

    /**
     * @param array $data
     * @param array $stats
     * @return AppModule
     * @throws \Exception
     */
    private static function importModule(array $data, array &$stats): AppModule
    {
        if (empty($data['id']) || empty($data['module'])) {
            throw new \Exception('Every module needs an "id" and a "module": ' . json_encode($data));
        }

        $module = AppModule::find($data['id']) ?? AppModule::where('module', $data['module'])->first();

        // Same module created separately on this server: take over the ID from the file
        if ($module && $module->id !== $data['id']) {
            $oldID = $module->id;
            AppModule::where('id', $oldID)->update(['id' => $data['id']]);
            AppModuleRoute::where('module_id', $oldID)->update(['module_id' => $data['id']]);
            $module = AppModule::find($data['id']);
            $stats['rekeyed']++;
        }

        $values = [
            'name'       => $data['name'] ?? NULL,
            'module'     => $data['module'],
            'controller' => $data['controller'] ?? NULL,
        ];

        if ($module) {
            $module->update($values);
            $stats['modules_updated']++;
            return $module;
        }

        $module = new AppModule($values + ['active' => (bool) ($data['active'] ?? FALSE)]);
        $module->id = $data['id'];
        $module->save();
        $stats['modules_created']++;
        return $module;
    }

    /**
     * @param AppModule $module
     * @param array $data
     * @param array $stats
     * @return void
     * @throws \Exception
     */
    private static function importRoute(AppModule $module, array $data, array &$stats): void
    {
        if (empty($data['id']) || empty($data['route_name'])) {
            throw new \Exception('Every route needs an "id" and a "route_name": ' . json_encode($data));
        }

        $route = AppModuleRoute::find($data['id'])
            ?? AppModuleRoute::where('module_id', $module->id)->where('route_name', $data['route_name'])->first();

        // Same route created separately on this server: take over the ID from the file
        if ($route && $route->id !== $data['id']) {
            AppModuleRoute::where('id', $route->id)->update(['id' => $data['id']]);
            $route = AppModuleRoute::find($data['id']);
            $stats['rekeyed']++;
        }

        $values = [
            'title'       => $data['title'] ?? NULL,
            'route_name'  => $data['route_name'],
            'method'      => $data['method'] ?? NULL,
            'module_id'   => $module->id,
            'resource_id' => self::resolveResourceID($data['resource'] ?? NULL),
            'position'    => $data['position'] ?? NULL,
            'divider'     => $data['divider'] ?? NULL,
        ];

        if ($route) {
            $route->update($values);
            $stats['routes_updated']++;
            return;
        }

        $route = new AppModuleRoute($values + ['active' => (bool) ($data['active'] ?? FALSE)]);
        $route->id = $data['id'];
        $route->save();
        $stats['routes_created']++;
    }

    /**
     * The ID of the resource with this name on this server, created when it doesn't exist.
     *
     * @param string|null $name
     * @return int|null
     */
    private static function resolveResourceID(?string $name): ?int
    {
        if ($name === NULL || $name === '') return NULL;

        $id = Resources::where('resources', $name)->orderBy('id')->value('id');
        return $id ?? Resources::create(['resources' => $name])->id;
    }
}
